# https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3777'
          config: 'baseUrl=http://localhost:3777'
          # no need to store the workspace, as there are no jobs after this one
          no-workspace: true
          # store the "cypress/failed" folder where the cyclope plugin
          # might store the full HTML page if a test fails
          post-steps:
            - store_artifacts:
                path: cypress/failed
